console.log('elements.js has been chained');

const $els = {
  landerBody: $('#land'),
  landerBodyDiv: $('#lander'),
  landerCenterImg: $('#imageDiv'),
  formField: $('#form'),
  playerInput: $('#name'),
  playBtn: $('#playBtn'),
  gameWrapper: $('#mainWrapper'),
  headerDiv: $('#headerDiv'),
  footerDiv: $('#footyDiv'),
  botCounter: $('#botCounter'),
  playerCounter: $('#playerCounter'),
  board: $('#boardDiv'),
  playGround: $('#playGround'),
  dropArea: $('#playerTarget'),
  botTarget: $('#botTarget'),
  playerDiv: $('#playerDiv'),
  botZeroCard: $('#b0'),
  botOneCard: $('#b1'),
  botTwoCard: $('#b2'),
  plZeroCard: $('#p0'),
  plOneCard: $('#p1'),
  plTwoCard: $('#p2'),
}
